CREATE DATABASE taskdb;

USE taskdb;

-- usuarios
CREATE TABLE TBL_USERS (
  C_ID_USER BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE VARCHAR(20) NOT NULL
);

-- tareas
CREATE TABLE TBL_TASKS (
  C_ID_TASK BIGINT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(150) NOT NULL,
  DESCRIPTION_TASK VARCHAR(500),
  COMPLETED BOOLEAN NOT NULL,
  C_ID_USER BIGINT NOT NULL,
  CONSTRAINT FK_TASK_USER FOREIGN KEY (C_ID_USER) REFERENCES TBL_USERS(C_ID_USER)
);
