spring.application.name=redpontis
server.port=8080
server.servlet.context-path=/milestones/api/

#conexion
#spring.datasource.url=jdbc:mysql://localhost:3306/taskdb?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456
spring.datasource.url=jdbc:mysql://db:3306/taskdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# configuracion Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.default-produces-media-type=application/json
springdoc.default-consumes-media-type=application/json

# metadatos Swagger
springdoc.info.title=Redpontis API
springdoc.info.description=Documentación de servicios Auth, Users y Tasks
springdoc.info.version=1.0